# Generated by Django 3.0.7 on 2020-06-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtail_image_import', '0001_create_import_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveIDMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(max_length=100)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Drive ID Mapping',
                'verbose_name_plural': 'Drive ID Mappings',
            },
        ),
    ]
