# Generated by Django 3.0.7 on 2020-06-25 03:32

from django.db import migrations, models
import django.db.models.deletion

from wagtail.images import get_image_model_string


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("wagtail_image_import", "0001_create_import_permission"),
        migrations.swappable_dependency(get_image_model_string()),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveIDMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_id", models.CharField(max_length=100)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=get_image_model_string(),
                    ),
                ),
            ],
            options={
                "verbose_name": "Drive ID Mapping",
                "verbose_name_plural": "Drive ID Mappings",
            },
        ),
    ]
