# Generated by Django 3.0.7 on 2020-06-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="exif_datetime",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customimage",
            name="md5_hash",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
